version = 0.1
[default.deploy.parameters]
stack_name = "grasp-backend"
resolve_s3 = true
s3_prefix = "grasp-backend"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "EnvType=\"NP\""
image_repositories = []
